name: Databricks CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Set Databricks Environment
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV

      - name: Update Repo (Auto Pull)
        run: |
          databricks repos update \
          --path "/Repos/om1821@gmail.com/databricks-poc" \
          --branch main

      # - name: Trigger Job
      #   run: |
      #     databricks jobs run-now \
      #     --job-id 771776842634842
      
      - name: Detect Changed Files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})" >> $GITHUB_ENV

      # ✅ CONDITIONAL JOB TRIGGERS

     
      - name: Trigger Job1
        run: |
          if grep -q "notebooks/job_notebook.py" files.txt; then
            echo "Triggering Job1"
            databricks jobs run-now --job-id 771776842634842
          else
            echo "Job1 not changed"
          fi
      
      - name: Trigger Job2
        run: |
          if grep -q "notebooks/etl_job1.py" files.txt; then
            echo "Triggering Job2"
            databricks jobs run-now --job-id 109514205917996
          else
            echo "Job2 not changed"
          fi
