name: Databricks CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Set Databricks Environment
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV

      - name: Update Repo (Auto Pull)
        run: |
          databricks repos update \
          --path "/Repos/om1821@gmail.com/databricks-poc" \
          --branch main

      # - name: Trigger Job
      #   run: |
      #     databricks jobs run-now \
      #     --job-id 771776842634842
      
      - name: Detect Changed Files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})" >> $GITHUB_ENV

      # ✅ CONDITIONAL JOB TRIGGERS

      - name: Trigger Job1
        if: contains(env.CHANGED_FILES, 'notebooks/job_notebook.py')
        run: databricks jobs run-now --job-id 771776842634842

      - name: Trigger Job2
        if: contains(env.CHANGED_FILES, 'etl_job1.py')
        run: databricks jobs run-now --job-id 109514205917996

